[package]
name = "systest"
version = "0.1.0"
authors = ["Dan Glastonbury <dan.glastonbury@gmail.com>"]

build = "build.rs"

[dependencies]
core-audio-sys = { path = "../core-audio-sys" }

[build-dependencies]
ctest = "0.1.7"